#!/usr/bin/env python3

import glob, bz2, lxml.etree



class WikiParse(object):
    def __init__(self, dir):
        super().__init__()
        self.dir = dir

    def _db(self):
        return glob.glob(self.dir+"/**/*.bz2", recursive=True)

    def find_article(self,title):
        for dbfile in self._db():
            fp = bz2.open(dbfile, 'rb')
            xml = lxml.etree.parse(fp)
            
