#!/usr/bin/env python3

# Copyright (c) 2017 Lorenzo Mureu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

''' A naive attempt at scraping Wikipedia through its API (given up)'''

import requests, json, lxml.html

class WikiStat:
    API_URL = "https://{}.wikipedia.org/w/api.php"

    def __init__(self, lang='en'):
        self.url = self.API_URL.format(lang)

    def _api_url(self):
        return

    def all_pages(self):
        apcontinue = ""
        while True:
            data = requests.get(self.url, params = {
                'action': 'query',
                'format': 'json',
                'list': 'allpages',
                'apcontinue': apcontinue,
                'apnamespace': 0,
                'apfilterredir': 'nonredirects'
            }).json()
            apcontinue = data['continue']['apcontinue']
            for page in data['query']['allpages']:
                yield page['title']

    def get_page(self, title):
        data = requests.get(self.url, params = {
            'action': 'parse',
            'page': title,
            'format': 'json',
            'prop': 'text'
        }).json()

        html = data['parse']['text']['*']
        doc = lxml.html.document_fromstring(html)
        text = doc.text_content()
        return text


def test():
    w = WikiStat('it')
    txt = w.get_page('Alghero')
    print(txt)

if __name__ == '__main__': test()
