#!/usr/bin/env python3

# Copyright (c) 2017 Lorenzo Mureu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

'''
Takes a (single, concatenated) wikiextractor file.
Generates a list of words sorted by frequency (ascending)
'''

import sys, re, pickle, operator

def norm(string):
    string = string.lower()
    from string import punctuation, whitespace
    rem = punctuation + whitespace
    trans = str.maketrans(rem, len(rem)*" ")
    return string.translate(trans)

if len(sys.argv) != 2:
    print("Syntax: {} <file>".format(sys.argv[0]), file=sys.stderr)
    exit(1)

N = 1386076
dic = {}
with open(sys.argv[1], 'r') as file:
    i = 0
    for line in file:
        if re.match('<doc', line):
            i += 1
            print('\r{} {:.3f}%'.format(i, 100*i/N), end='', flush=True)
            continue
        if re.match('</doc', line): continue
        line = norm(line)
        for word in line.split(' '):
            if word in dic:
                dic[word] += 1
            else:
                dic[word] = 1

sorted_list = sorted(dic.items(), key = operator.itemgetter(1))

with open("sorted_list_i.pickle", "wb") as f:
    pickle.dump(sorted_list, f)

print("done")
